language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules

install:
- npm install

script:
- node shins.js

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  repo: tomochain/apidocs
  local-dir: .
  target-branch: gh-pages
  fqdn: apidocs.tomochain.com
  on:
    branch: master
